# Generated by Django 3.0.5 on 2020-06-17 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vote', '0003_user_clicknum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='clicknum',
            field=models.IntegerField(default=6, verbose_name='剩余投票数'),
        ),
    ]
